<a href="https://colab.research.google.com/github/abxda/python/blob/main/UP_Semana_1_Viernes_y_S%C3%A1bado_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

# Creando un array NumPy
array_np = np.array([1, 2, 3, 4, 5])
print(array_np)

In [ ]:
print([1, 2, "tres", 4, 5])

In [ ]:
array_np + 2

In [ ]:
type(array_np)

In [ ]:
array_from_tuple = np.array((1, 2, 3, 4, 5))
print(array_from_tuple)

In [ ]:
# Lista de Python
lista_py = [1, 2, 3, 4, 5]

In [ ]:
array_int32 = np.array([1, 2, 3, -4, -5], dtype=np.int32)
array_int64 = np.array([1, 2, 3, -4, -5], dtype=np.int64)

In [ ]:
array_int32

In [ ]:
array_int64

In [ ]:
# Calcular el tamaño en memoria
tamaño_int32 = array_int32.nbytes
tamaño_int64 = array_int64.nbytes

print(f"El tamaño de memoria de array_int32 es: {tamaño_int32} bytes")
print(f"El tamaño de memoria de array_int64 es: {tamaño_int64} bytes")

In [ ]:
array_float32 = np.array([1.5, 2.5, 3.5, -4.5], dtype=np.float32)
array_float64 = np.array([1.5, 2.5, 3.5, -4.5], dtype=np.float64)
# Calcular el tamaño en memoria
tamaño_float32 = array_float32.nbytes
tamaño_float64 = array_float64.nbytes

print(f"El tamaño de memoria de array_float32 es: {tamaño_float32} bytes")
print(f"El tamaño de memoria de array_float64 es: {tamaño_float64} bytes")

In [ ]:
array_string = np.array(["apples", "bananas", "cherry"], dtype=np.bytes_)
tamaño_string = array_string.nbytes
print(f"El tamaño de memoria de array_string es: {tamaño_string} bytes")

In [ ]:
array_string = np.array(["apples", "bananas", "cherry"], dtype=np.str_)
tamaño_string = array_string.nbytes
print(f"El tamaño de memoria de array_string es: {tamaño_string} bytes")

In [ ]:
strings = np.array(["Hola", "mundo", "esto", "es", "una", "prueba"], dtype=np.bytes_)
tamaño_string2 = strings.nbytes
print(f"El tamaño de memoria de array_string2 es: {tamaño_string2} bytes")

In [ ]:
strings = np.array(["Hola", "mundo", "esto", "es", "uña", "prueba"], dtype=np.str_)
tamaño_string2 = strings.nbytes
print(f"El tamaño de memoria de array_string2 es: {tamaño_string2} bytes")

In [ ]:
strings = np.array(["Hola", "mundo", "esto", "es", "uña", "prueba"], dtype=np.str_)
tamaño_string2 = strings.nbytes
print(f"El tamaño de memoria de array_string2 es: {tamaño_string2} bytes")

In [ ]:
# Crear un array de NumPy con emojis y especificar el tipo como unicode
emojis_array = np.array(["😀", "😂", "🤔", "😍", "🙄", "😎"], dtype=np.str_)
# Calcular el tamaño en memoria del array de emojis
tamaño_emojis = emojis_array.nbytes
# Imprimir el tamaño en memoria del array de emojis
print(f"El tamaño de memoria de emojis_array es: {tamaño_emojis} bytes")

In [ ]:
# Crear un array de NumPy con emojis y especificar el tipo como unicode
emojis_array = np.array(["😀", "😂", "🤔", "😍", "🙄", "😎"], dtype=np.bytes_)
# Calcular el tamaño en memoria del array de emojis
tamaño_emojis = emojis_array.nbytes
# Imprimir el tamaño en memoria del array de emojis
print(f"El tamaño de memoria de emojis_array es: {tamaño_emojis} bytes")

In [ ]:
import numpy as np
import time

# Tamaño grande del conjunto de datos
tamaño = 1000000

inicio_numpy = time.time()
array_np = np.arange(tamaño)
array_np_modificado = array_np + 2
fin_numpy = time.time()
tiempo_numpy = fin_numpy - inicio_numpy
print( f"Operación con array de NumPy: Resultado {array_np_modificado[:10]}  Tiempo: {tiempo_numpy}")

Operación con array de NumPy: Resultado [ 2  3  4  5  6  7  8  9 10 11]  Tiempo: 0.010958194732666016


In [ ]:
import time

# Definimos el tamaño de la lista
tamaño = 1000000  # Por ejemplo, un millón de elementos
inicio_lista = time.time()
lista_py = list(range(tamaño))
lista_py_modificada = []
for x in lista_py:
    lista_py_modificada.append(x + 2)
fin_lista = time.time()
tiempo_lista_for = fin_lista - inicio_lista
print(f"Operación con listas de Python: Resultado {lista_py_modificada[:10]} Tiempo: {tiempo_lista_for}")



Operación con listas de Python: Resultado [2, 3, 4, 5, 6, 7, 8, 9, 10, 11] Tiempo: 0.19133543968200684


In [ ]:
inicio_lista = time.time()
lista_py = list(range(tamaño))
lista_py_modificada = [x + 2 for x in lista_py]
fin_lista = time.time()
tiempo_lista = fin_lista - inicio_lista
print( f"Operación con listas de Python: Resultado {lista_py_modificada[:10]}  Tiempo: {tiempo_lista}")

Operación con listas de Python: Resultado [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]  Tiempo: 0.11118960380554199


In [ ]:
tiempo_lista_for/tiempo_numpy

17.46048909969105

In [ ]:
tiempo_lista/tiempo_numpy

10.146708150211044

In [ ]:
# Creación de un arreglo unidimensional para almacenar edades
edades = np.array([20, 22, 25, 21, 19])

# Impresión del arreglo de edades
print(edades)

[20 22 25 21 19]


In [ ]:
edades.shape

(5,)

In [ ]:
temperaturas = np.array([
    [18, 20, 22, 24, 23, 21, 19],
    [19, 21, 23, 25, 24, 22, 20],
    [20, 22, 24, 26, 25, 23, 21],
    [21, 23, 25, 27, 26, 24, 22],
    [22, 24, 26, 28, 27, 25, 23],
    [23, 25, 27, 29, 28, 26, 24],
    [24, 26, 28, 30, 29, 27, 25],
])

# Impresión de la matriz de temperaturas
print(temperaturas)

[[18 20 22 24 23 21 19]
 [19 21 23 25 24 22 20]
 [20 22 24 26 25 23 21]
 [21 23 25 27 26 24 22]
 [22 24 26 28 27 25 23]
 [23 25 27 29 28 26 24]
 [24 26 28 30 29 27 25]]


In [ ]:
temperaturas.shape

(7, 7)

In [ ]:
# Supongamos que solo representamos los primeros 7 momentos del día para simplificar
# Registro de temperaturas para varias ciudades a lo largo del año por momento del día
temperaturas_pais = np.array([
    [ # Ciudad 1
        [18, 20, 22, 24, 23, 21, 19],
        [19, 21, 23, 25, 24, 22, 20],
        # ... (resto de días del año)
    ],
    [ # Ciudad 2
        [20, 22, 24, 26, 25, 23, 21],
        [21, 23, 25, 27, 26, 24, 22],
        # ... (resto de días del año)
    ],
    # ... (resto de ciudades)
])

# La forma (shape) del arreglo nos da una idea de la estructura de los datos
print(temperaturas_pais)

[[[18 20 22 24 23 21 19]
  [19 21 23 25 24 22 20]]

 [[20 22 24 26 25 23 21]
  [21 23 25 27 26 24 22]]]


In [ ]:
temperaturas_pais.shape

(2, 2, 7)

In [ ]:
import numpy as np

# Creando dos arrays para demostración
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Operaciones básicas
suma = a + b
resta = a - b
multiplicacion = a * b
division = a / b

print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)
print("División:", division)


In [ ]:
# Creando un array para demostración
c = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Funciones estadísticas
media = np.mean(c)
mediana = np.median(c)
varianza = np.var(c)
desviacion_estandar = np.std(c)

print("Media:", media)
print("Mediana:", mediana)
print("Varianza:", varianza)
print("Desviación Estándar:", desviacion_estandar)


In [ ]:
# 12 meses de datos en un array 1D
datos = np.arange(1, 13)
print(datos)
print(datos.shape)
# Reorganizar en una matriz 2D (1 año x 12 meses)
datos_reshape = datos.reshape((1, 12))
print("Datos reorganizados:\n", datos_reshape)
print(datos_reshape.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
Datos reorganizados:
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]]
(1, 12)


In [ ]:
datos_reshape2 = datos.reshape((2, 3, 2))
print(datos_reshape2)

In [ ]:
datos_reshape2.shape

In [ ]:
datos.shape

In [ ]:
datos_reshape.shape

In [ ]:
# Redimensionar el array para incluir 2 años (replicando datos)
datos_resized = np.resize(datos, (2, 12))
print("Datos redimensionados:\n", datos_resized)


In [ ]:
datos_resized.shape

In [ ]:
# Concatenar dos arrays 1D
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
array_concatenado = np.concatenate((array_a, array_b))
print("Array concatenado:", array_concatenado)

# Dividir un array en 3 partes iguales
array_dividido = np.split(array_concatenado, 3)
print("Array dividido:", array_dividido)


In [ ]:
type(array_dividido)

In [ ]:
type(array_concatenado)

In [ ]:
import numpy as np

# Creamos un arreglo con NumPy
arr = np.array([4, 7, 2])
#      INDEX    0  1  2

In [ ]:
arr.shape

In [ ]:
arr.ndim

In [ ]:
# Imprimimos el segundo elemento del arreglo
print(arr[1])

In [ ]:
arr = np.array([[2, 3, 4],
                [1, 2, 5],
                [3, 4, 3]])



In [ ]:
arr.ndim

In [ ]:
arr.shape

In [ ]:
arr

In [ ]:
      [(0) [ 2,  3,  4],
            (0) (1) (2)
       (1) [ 1,  2,  5],
       (2) [ 3,  4,  3]]

In [ ]:
print(arr[1, 2])

In [ ]:
arr.ndim

In [ ]:
arr = np.array([[[2, 1], [4, 5], [6, 2]],
                [[3, 4], [7, 6], [10, 2]]])


In [ ]:
arr.ndim

In [ ]:
print(arr[1, 2, 0])

In [ ]:
arr = np.array([[2, 3, 4],  #-3
                [1, 2, 5],  #-2
                [3, 4, 3]]) #-1


In [ ]:
print(arr[-2, -2])

In [ ]:
arr = np.array([2,3,1,5,6])
print(arr[1:4])  # Esto imprimirá [3, 1, 5]


In [ ]:
print(arr[:4])  # Resultado: [2, 3, 1, 5]
print(arr[1:])  # Resultado: [3, 1, 5, 6]
print(arr[:])   # Resultado: [2, 3, 1, 5, 6]


In [ ]:
arr = np.array([[2, 3, 4, 3, 6],
                [1, 2, 5, 7, 5],
                [3, 4, 3, 3, 5],
                [5, 6, 3, 2, 1],
                [4, 3, 3, 5, 5],
                [3, 1, 4, 5, 6]])


In [ ]:
print(arr[1:3, 1:])

In [ ]:
print(arr[1])

In [ ]:
arr = np.array([[[2, 1], [4, 5], [6, 2]],
                [[3, 4], [7, 6], [10, 2]]])


In [ ]:
print(arr[:, 1:, :])

In [ ]:
arr = np.array([[[2, 1], [4, 5], [6, 2]],
                [[3, 4], [7, 6], [10, 2]]])


In [ ]:
import numpy as np

# Creamos un arreglo unidimensional con edades
edades = np.array([20, 22, 25, 27, 30])

In [ ]:
edades

In [ ]:
# Generamos una máscara booleana para edades mayores a 25
mascara = edades > 25

In [ ]:
mascara

In [ ]:



# Aplicamos la máscara para seleccionar solo las edades mayores a 25
edades_mayores = edades[mascara]

print(edades_mayores)  # Salida: [27 30]


In [ ]:
print(arr[:, 1:, 0])

In [ ]:
from skimage import io
import matplotlib.pyplot as plt
import numpy as np
# URL de la imagen en formato raw
url_imagen = 'https://raw.githubusercontent.com/abxda/python/main/img/taquito_01.jpeg'

# Leer la imagen desde la URL
taquito = io.imread(url_imagen)

# Mostrar la imagen
plt.imshow(taquito)

In [ ]:
type(taquito)

In [ ]:
taquito.shape

In [ ]:
taquito

In [ ]:
taquito.shape

In [ ]:
# Supongamos que 'taquito' es un ndarray que representa una imagen con píxeles

# Recortar la parte superior izquierda de la imagen
top_left_quarter = taquito[:taquito.shape[0]//2, :taquito.shape[1]//2]

# Crear una máscara para la mitad inferior de la imagen
mask_lower_half = np.zeros_like(taquito, dtype=bool)
mask_lower_half[taquito.shape[0]//2:] = True

# Oscurecer la mitad inferior de la imagen
taquito_darkened_lower = taquito.astype(float)  # Convertir a flotante
taquito_darkened_lower[mask_lower_half] *= 0.5  # Oscurecer los píxeles
taquito_darkened_lower = taquito_darkened_lower.astype(np.uint8)  # Convertir de vuelta a uint8 si es necesario


# Mostrar la imagen original
plt.imshow(taquito)
plt.title('Original')


In [ ]:
plt.imshow(top_left_quarter)
plt.title('Esquina Superior Izquierda')
plt.show()

In [ ]:
plt.imshow(taquito_darkened_lower)
plt.title('Mitad Inferior Oscurecida')
plt.show()


In [ ]:
# Creemos un efecto espejo
taquito_reflejado = taquito[:, ::-1]

plt.imshow(taquito_reflejado)
plt.axis('off')
plt.show()


In [ ]:
# Digamos que queremos resaltar solo los colores más brillantes de Taquito
luz_alta = taquito > 200  # Un umbral para 'brillo alto'
taquito_brillante = taquito * luz_alta
plt.imshow(taquito_brillante)
plt.show()
